In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('car_dubplicates.csv')

In [3]:
df

   model_id model_name  color   brand
0         1       leaf  black  nissan
1         2       leaf  black  nissan
2         3    model s  black   tesla
3         4    model x  white   tesla
4         5       alto  white   tesla
5         6       alto  black  maruti
6         7       alto  black  maruti

In [5]:
df.iloc[0:,1: ].drop_duplicates()

  model_name  color   brand
0       leaf  black  nissan
2    model s  black   tesla
3    model x  white   tesla
4       alto  white   tesla
5       alto  black  maruti

In [8]:
df.sort_values(by='model_id', ascending=True).drop_duplicates(subset=['model_name', 'color', 'brand'], keep='first')

   model_id model_name  color   brand
0         1       leaf  black  nissan
2         3    model s  black   tesla
3         4    model x  white   tesla
4         5       alto  white   tesla
5         6       alto  black  maruti