In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('teams.csv')

In [4]:
df

   teams
0    rcb
1     mi
2    csk
3    srh
4     dd
5     mi
6  jammu
7     hp

In [5]:
df.drop_duplicates(inplace=True, ignore_index=True)

In [6]:
df

   teams
0    rcb
1     mi
2    csk
3    srh
4     dd
5  jammu
6     hp

In [7]:
df['team_id'] = np.arange(len(df))

In [8]:
df

   teams  team_id
0    rcb        0
1     mi        1
2    csk        2
3    srh        3
4     dd        4
5  jammu        5
6     hp        6

In [9]:
game = df.merge(df, how='cross', suffixes=['_left', '_right'])

In [10]:
game = game[game['team_id_left'] < game['team_id_right']]

In [12]:
game = game[['teams_left', 'teams_right']]

In [13]:
game

   teams_left teams_right
1         rcb          mi
2         rcb         csk
3         rcb         srh
4         rcb          dd
5         rcb       jammu
6         rcb          hp
9          mi         csk
10         mi         srh
11         mi          dd
12         mi       jammu
13         mi          hp
17        csk         srh
18        csk          dd
19        csk       jammu
20        csk          hp
25        srh          dd
26        srh       jammu
27        srh          hp
33         dd       jammu
34         dd          hp
41      jammu          hp